### PR TITLE
Create Language Reading Diplo

### PR DESCRIPTION
**Pull request by Julesol**

### CODE REVIEW

**Comment by rafacarrascosa** [comment]
Hi Julesol, would you mind expanding on your PR?

**Comment by Julesol** [comment]
Not a problem, sorry about curtness of the original request.

I'm designing a model that is to look at governmental declarations from
various foreign offices and state departments, to find and examine
relationships between states in particular that of sanctions and other
policy actions. (i.e. searching in official releases for statements
describing changes in laws governing trade between two states or a
declaration of a new treaty.)

Because most reports and available data is presented through natural
language spanning years and remains , rather than in a prepared database,
this means it will be easier to use a program to collect information
directly rather than going through the process of manual examination and
sorting of information.

I was made aware of your program not too long ago and was hoping to make
use of it for such a search.


On Tue, May 19, 2015 at 7:10 AM, Rafael Carrascosa <notifications@github.com

**Comment by rafacarrascosa** [comment]
That's a very interesting project :)
If your project is not secret (or something) we would be happy to hear how iepy is working for you and to give you a hand with the troubleshooting.

I believe that you are new to github, so I'll explain a few things, in case you already know just ignore them.
Pull requests are used to suggest a change or improvement to the original authors of a project. From the project author's point of view, to accept a pull request depends on whether the change is an improvement for the whole community using the project.

In this case, this pull request is suggesting to add a new file "Language Reading Diplo" with a single empty line to the "master copy" of the iepy project. This change could be an improvement to your use of iepy but it will surely be unnecessary for the rest of the community that uses iepy. Therefore I should reject this pull request... unless you can argument as to why this pull request good for the community, that's why I asked you "would you mind expanding on your PR?".

**BUT**, you can **always** have you private copy of this project, edit it, improve it, change it, and make money with it without ever having to explain or justify or share changes or share profits with anyone but yourself because: Iepy is an open source project with BSD license.

So, my recommendation to you would be to make a fork of this project (or just clone it) and modify it for the application you had in mind. If later in the future you are feeling generous, philanthropic and open-soursish you can share your improvements back to the original project by making pull requests.

Bests!

**Comment by Julesol** [comment]
Thank you,

Yes, I am very new to github. (only just signed up), sorry about the mess I
made for you. I'm still learning about how this all works.

I messed up in my attempt to fork the project, therefore please reject this
pull request. My previous programming experience has never made use of
collaborative space before and I was mistaken in how to get proper access.

And once I get something worth sharing, I will be happy to share it back
with you. There shouldn't be a problem with that.

- Thank you once again for your time and for designing this program in the
first place.

**Comment by rafacarrascosa** [comment]
Good luck!

**Pull request closed without merging**
